//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntrevistaEntities : DbContext
    {
        public EntrevistaEntities()
            : base("name=EntrevistaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Personas> Personas { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
    
        public virtual int sp_EliminaPersona(Nullable<int> id_Persona)
        {
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("id_Persona", id_Persona) :
                new ObjectParameter("id_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaPersona", id_PersonaParameter);
        }
    
        public virtual int sp_ModificaPersona(Nullable<int> id_Persona, string nombre, string correo, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito)
        {
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("id_Persona", id_Persona) :
                new ObjectParameter("id_Persona", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaPersona", id_PersonaParameter, nombreParameter, correoParameter, provinciaParameter, cantonParameter, distritoParameter);
        }
    
        public virtual int sp_RegistraPersona(string nombre, string correo, Nullable<int> provincia, Nullable<int> canton, Nullable<int> distrito)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var provinciaParameter = provincia.HasValue ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(int));
    
            var cantonParameter = canton.HasValue ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(int));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistraPersona", nombreParameter, correoParameter, provinciaParameter, cantonParameter, distritoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCantones_Result> sp_RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCantones_Result>("sp_RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_Result> sp_RetornaDistritos(string nombre, Nullable<int> id_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_Result>("sp_RetornaDistritos", nombreParameter, id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPersona_Result> sp_RetornaPersona()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPersona_Result>("sp_RetornaPersona");
        }
    
        public virtual ObjectResult<sp_RetornaPersonas_Result> sp_RetornaPersonas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPersonas_Result>("sp_RetornaPersonas");
        }
    
        public virtual ObjectResult<sp_RetornaProvincias_Result> sp_RetornaProvincias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaProvincias_Result>("sp_RetornaProvincias", nombreParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPersonaID_Result> sp_RetornaPersonaID(Nullable<int> id_Persona)
        {
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("Id_Persona", id_Persona) :
                new ObjectParameter("Id_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPersonaID_Result>("sp_RetornaPersonaID", id_PersonaParameter);
        }
    }
}
